package org.cloudbus.cloudsim.failure;

import java.util.List;

import org.cloudbus.cloudsim.failure.FailureEvent;


/**
 * This interface defines what a Failure model should provide. A failure
 * model generates a list of availability/unavailability that can be happened in a resource (e.g., a PE)
 * 
 *
 * @author   Bahman Javadi
 * @author   Yogesh Sharma
 * @since    Cloudsim Toolkit 3.0.3
 * 
 * @see FailureFileReader
 */
public interface FailureModel {
	
	/**
	 * Returns a list with the jobs generated by the workload.
	 * @return a list with the jobs generated by the workload.
	 */
	List<FailureEvent> generateFailure();	
	
}
